Demonstrating how to create arrays in NumPy using the following functions:

In [5]:
##importing numpy
import numpy as np

##`array()`
array = np.array([1,3,5,7,2])
print(array)

print("-" * 30)

arr = np.array([[23,45,65,64],[28,45,87,56]])
print(arr)

print("-" * 30)

A = np.array([[2,3,5,6],[5,9,0,4],[5,8,7,4],[7,4,8,5]])
print(A)

[1 3 5 7 2]
------------------------------
[[23 45 65 64]
 [28 45 87 56]]
------------------------------
[[2 3 5 6]
 [5 9 0 4]
 [5 8 7 4]
 [7 4 8 5]]


In [7]:
##`arange()` -It creates an array with evenly spaced values within a given range.

print(np.arange(7,14,2))      ##["start" = 7 , "end" =14 , "step" = 2]
print(np.arange(1,25,5)) 

[ 7  9 11 13]
[ 1  6 11 16 21]


In [11]:
##`zeros()`
a = np.zeros([2,3])
print(a)

print("-" * 30)

b = np.zeros([3,5] , dtype = "int32")
print(b) 

print("-" * 30)

c = np.zeros([4,3] , dtype = "float64")
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]
------------------------------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
------------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
##`ones()`
a = np.ones([2,3])
print(a)

print("-" * 30)

b = np.ones([3,5] , dtype = "int32")
print(b) 

print("-" * 30)

c = np.ones([4,3] , dtype = "float64")
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
------------------------------
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
------------------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
##`full()`
a = np.full([2,3] ,99)
print(a)

b = np.full((3,5) ,240)
print(b)

[[99 99 99]
 [99 99 99]]
[[240 240 240 240 240]
 [240 240 240 240 240]
 [240 240 240 240 240]]


In [15]:
##`eye()` - creates an identity matrix.
c = np.eye(3)
print(c)

b = np.identity(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
##`random()`
a = np.random.rand(3,4)   ## 3 x 4 matrix
print(a)

a = np.random.randint(1,7, size = (3,4))   ##number between 1 and 7 ,  3 x 4 matrix
print(a)

[[0.29973454 0.06491955 0.91002437 0.64891868]
 [0.28455946 0.71788705 0.81280023 0.19427567]
 [0.68616868 0.73067693 0.75409408 0.75860999]]
[[3 5 5 6]
 [4 1 3 1]
 [4 6 6 2]]


In [26]:
##`linspace()` - create an array of evenly spaced numbers over a specified interval.
b = np.linspace(2, 5, 10)  ##(starting value of the sequence, end value of the sequence,number of samples)
print(b)

b = np.linspace(2, 5, 2)  ##(starting value of the sequence, end value of the sequence,number of samples)
print(b)

[2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.        ]
[2. 5.]


#### How to retrieve various attributes of NumPy arrays

In [31]:
a = np.random.randint(1,7, size = (3,3))  
print(a)

[[3 3 3]
 [3 2 6]
 [6 2 1]]


In [37]:
##The number of dimensions
print(f"Number of dimensions {np.ndim(a)}")
a.ndim

##The shape of the array 
print(f"Shape of array {a.shape}")

##The total count of elements
print(f"Total count of elements {a.size}")

##The data type of the elements
print(f"Data type of elemts {a.dtype}")

##The memory size of each element
print(f"Memory size of elements {a.itemsize}")

##The raw data buffer - The underlying block of memory where all the array’s data values are stored, before any formatting is applied.
print(f"Memory buffer of the data {a.data}")

Number of dimensions 2
Shape of array (3, 3)
Total count of elements 9
Data type of elemts int32
Memory size of elements 4
Memory buffer of the data <memory at 0x0000020C8FFA5560>


#### How to access and modify specific elements within a NumPy array

In [39]:
A = np.array([[3,5,4,7,8],[2,1,9,0,12],[24,36,48,54,60]])
print(A)

[[ 3  5  4  7  8]
 [ 2  1  9  0 12]
 [24 36 48 54 60]]


In [44]:
##Access element value 0 from A
print(A[1,3])

##Access element value 24 from A
print(A[2,0])

##Modify 1st row third element(which is 4) as 200
A[0,2] = 200
print(A)

0
24
[[  3   5 200   7   8]
 [  2   1   9   0  12]
 [ 24  36  48  54  60]]


#### Slice arrays to extract subarrays from a larger array , demonstrate how these subarrays can be modified.

In [45]:
A = np.array([[22,44,51,34,46],
              [23,45,56,25,46],
              [35,37,69,44,69],
              [46,54,28,34,34],
              [35,37,56,25,69]])
print(A)

[[22 44 51 34 46]
 [23 45 56 25 46]
 [35 37 69 44 69]
 [46 54 28 34 34]
 [35 37 56 25 69]]


In [48]:
##Slicing to get the subarray
B = A[1:3 , 1:4]  ##take 2nd row and 3rd row (1:3) , then from columns 2nd column to 4th column (1:4)
print(B)

##Modifying the subarrays - change 56 to 34
B[0,1] = 34
B

[[45 56 25]
 [37 69 44]]


array([[45, 34, 25],
       [37, 69, 44]])

#### Demonstrate how to alter the structure of an array using the `reshape()` function.

In [4]:
before = np.random.rand(4,3)
print(before)

[[0.75518535 0.54139115 0.59767377]
 [0.56239075 0.9197612  0.18425429]
 [0.48505349 0.45815779 0.30906186]
 [0.13544653 0.86325011 0.85775437]]


In [7]:
after = before.reshape(2, 6)
print(after)

after = before.reshape(3,4)
print(after)

after = before.reshape(6,2)
print(after)

[[0.75518535 0.54139115 0.59767377 0.56239075 0.9197612  0.18425429]
 [0.48505349 0.45815779 0.30906186 0.13544653 0.86325011 0.85775437]]
[[0.75518535 0.54139115 0.59767377 0.56239075]
 [0.9197612  0.18425429 0.48505349 0.45815779]
 [0.30906186 0.13544653 0.86325011 0.85775437]]
[[0.75518535 0.54139115]
 [0.59767377 0.56239075]
 [0.9197612  0.18425429]
 [0.48505349 0.45815779]
 [0.30906186 0.13544653]
 [0.86325011 0.85775437]]


#### The use of the following NumPy functions with examples:

(a) Arithmetic Operations:
`np.add`, `np.subtract`, `np.multiply`, `np.divide`, `np.floor_divide`, `np.power`, and
`np.mod`.

In [16]:
array_1 = np.array([10, 20, 30, 40])
array_2 = np.array([2, 5, 6, 8])

add = np.add(array_1 , array_2)
print(f"The addition of two arrays are {add}")

subtract = np.subtract(array_1 , array_2)
print(f"The difference of two arrays are {subtract}")

multiply = np.multiply(array_1 , array_2)
print(f"The product of two arrays are {multiply}")

division = np.divide(array_1 , array_2)
print(f"The division of two arrays are {division}")

floor_division = np.floor_divide(array_1 , array_2)
print(f"The floor division {floor_division}")

power = np.power(array_1 , array_2)
print(f"The power {power}")

mod = np.mod(array_1 ,array_2)
print(f"The mod {mod}")


The addition of two arrays are [12 25 36 48]
The difference of two arrays are [ 8 15 24 32]
The product of two arrays are [ 20 100 180 320]
The division of two arrays are [5. 4. 5. 5.]
The floor division [5 4 5 5]
The power [          100       3200000     729000000 6553600000000]
The mod [0 0 0 0]


(b) Exponential and Logarithmic Functions:**
`np.exp`, `np.exp2`, `np.log`, `np.log2`, and `np.log10`.

In [17]:
arr = np.array([1, 2, 8, 10])

exp = np.exp(arr)
print(f"exp(arr):{exp}")

exp2 = np.exp2(arr)
print(f"exp2(arr):{exp2}")

log = np.log(arr)
print(f"log(arr):{log}")

log2 = np.log2(arr)
print(f"log2(arr):{log2}")

log10 = np.log10(arr)
print(f"log10(arr):{log10}")

exp(arr):[2.71828183e+00 7.38905610e+00 2.98095799e+03 2.20264658e+04]
exp2(arr):[   2.    4.  256. 1024.]
log(arr):[0.         0.69314718 2.07944154 2.30258509]
log2(arr):[0.         1.         3.         3.32192809]
log10(arr):[0.         0.30103    0.90308999 1.        ]


(c) Aggregate Functions:
`np.sum`, `np.prod`, `np.mean`, `np.std`, `np.var`, `np.min`, `np.max`, `np.argmin`,
`np.argmax`, `np.median`, `np.percentile`, `np.any`, and `np.all`.

In [24]:
array_1 = np.array([[10, 20, 30, 40], [3, 8, 2,1]])

print(f"the sum of array 1 : {np.sum(array_1)}")
print(f"the prod of array 1 : {np.prod(array_1)}")
print(f"the mean of array 1 : {np.mean(array_1)}")
print(f"the std of array 1 : {np.std(array_1)}")
print(f"the var of array 1 : {np.var(array_1)}")
print(f"the min of array 1 : {np.min(array_1)}")
print(f"the max of array 1 : {np.max(array_1)}")
print(f"the index of the minimum of array 1 : {np.argmin(array_1)}")
print(f"the index of the maximum of array 1 : {np.argmax(array_1)}")
print(f"the median of array 1 : {np.median(array_1)}")
print(f"the percentile of array 1 : {np.percentile(array_1 , 25)}")

print(np.any(array_1 > 25))
print(np.any(array_1 < 50, axis = 0))
print(np.any(array_1 > 25, axis = 1))

print(np.all(array_1 % 5 == 0))

the sum of array 1 : 114
the prod of array 1 : 11520000
the mean of array 1 : 14.25
the std of array 1 : 13.47915056670857
the var of array 1 : 181.6875
the min of array 1 : 1
the max of array 1 : 40
the index of the minimum of array 1 : 7
the index of the maximum of array 1 : 3
the median of array 1 : 9.0
the percentile of array 1 : 2.75
True
[ True  True  True  True]
[ True False]
False



a) Create a 2D NumPy array (4x5) with random integers between 10 and 99.


In [27]:
array = np.random.randint(10,100, size = (4,5))
print(array)

[[65 95 16 32 99]
 [43 14 13 20 54]
 [98 65 18 70 17]
 [45 49 40 45 36]]


b) Make a deep copy of the array and demonstrate that modifying the copy does not
affect the original.

In [36]:
copy_array = array.copy()

copy_array[1,0:3] = 89
print(f"The orginal array:\n {array}")
print(f"The Modified copied array:\n {copy_array}")


The orginal array:
 [[65 95 16 32 99]
 [43 14 13 20 54]
 [98 65 18 70 17]
 [45 49 40 45 36]]
The Modified copied array:
 [[65 95 16 32 99]
 [89 89 89 20 54]
 [98 65 18 70 17]
 [45 49 40 45 36]]


c) Sort the copied array:
  First, sort each row in ascending order.
  Then, sort each column in ascending order (based on the sorted rows).

In [41]:
row_sort = np.sort(copy_array , axis = 1)
print(row_sort)

row_column_sort = np.sort(row_sort , axis = 0)
print(row_column_sort)

[[16 32 65 95 99]
 [20 54 89 89 89]
 [17 18 65 70 98]
 [36 40 45 45 49]]
[[16 18 45 45 49]
 [17 32 65 70 89]
 [20 40 65 89 98]
 [36 54 89 95 99]]


d) Display the following:
(i) The original array (unchanged).
(ii) The row-sorted array.
(iii) The final row-and-column sorted array.

In [43]:
print(f"The orginal array:\n {array}")
print(f"The row sorted array:\n {row_sort}")
print(f"The final row-and-column sorted array:\n {row_column_sort}")

The orginal array:
 [[65 95 16 32 99]
 [43 14 13 20 54]
 [98 65 18 70 17]
 [45 49 40 45 36]]
The row sorted array:
 [[16 32 65 95 99]
 [20 54 89 89 89]
 [17 18 65 70 98]
 [36 40 45 45 49]]
The final row-and-column sorted array:
 [[16 18 45 45 49]
 [17 32 65 70 89]
 [20 40 65 89 98]
 [36 54 89 95 99]]


e) Verify that the original array is not modified.

In [50]:
print(array)

##or

if np.array_equal(array, row_column_sort):
    print("Original got modified!")
else:
    print("Original is unchanged.")

[[65 95 16 32 99]
 [43 14 13 20 54]
 [98 65 18 70 17]
 [45 49 40 45 36]]
Original is unchanged.


#### Advanced use cases of fancy indexing:

Extract all even numbers from a given 2D array.

In [15]:
import numpy as np
numbers = np.random.randint(10,70, size = (5,6))  
print(numbers)

even_numbers = numbers%2==0
print(even_numbers)

numbers[even_numbers]

[[62 66 24 45 46 23]
 [52 29 36 39 10 43]
 [28 33 30 39 12 23]
 [40 50 18 39 69 14]
 [67 51 27 65 64 53]]
[[ True  True  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True  True  True False False  True]
 [False False False False  True False]]


array([62, 66, 24, 46, 52, 36, 10, 28, 30, 12, 40, 50, 18, 14, 64],
      dtype=int32)

Select every alternate row from a 2D array using an index array.

In [18]:
alternate_rows = np.array([0,2,4])
numbers[alternate_rows]

array([[62, 66, 24, 45, 46, 23],
       [28, 33, 30, 39, 12, 23],
       [67, 51, 27, 65, 64, 53]], dtype=int32)

Use two arrays of indices to extract elements from specific row-column positions in a
matrix.

In [19]:
row_indices = np.array([0,1,2])
column_indices = np.array([0,2,3])
numbers[row_indices , column_indices]

array([62, 36, 39], dtype=int32)

#### Illustrate various sorting techniques

Sort a 1D array in descending order.
Sort a 2D array along columns and then along rows, and observe the results.

In [27]:
array_1 = np.random.randint(10,70, size = (5,)) 
print(array_1)

print(f"Sort of 1D array {np.sort(array_1)}\n")

array_2 = np.random.randint(20,80, size = (4,4)) 
print(array_2)

columns_sort = np.sort(array_2 , axis = 0)
print(f"Sort of 2D array along columns {columns_sort}\n") 

rows_sort = np.sort(array_2 , axis = 1)
print(f"Sort of 2D array along rows {rows_sort}\n") 


[29 30 37 29 62]
Sort of 1D array [29 29 30 37 62]

[[46 39 77 32]
 [56 39 64 59]
 [65 39 47 24]
 [25 56 44 55]]
Sort of 2D array along columns [[25 39 44 24]
 [46 39 47 32]
 [56 39 64 55]
 [65 56 77 59]]

Sort of 2D array along rows [[32 39 46 77]
 [39 56 59 64]
 [24 39 47 65]
 [25 44 55 56]]



Use `argsort()` to sort one array based on the sorted order of another array (e.g.,
sorting student names based on their marks).

In [29]:
marks = np.array([85, 92, 78, 95, 88])
student_names = np.array(['Bob', 'Alice', 'Charlie', 'David', 'Eve'])

sort = np.argsort(marks)

print(student_names[sort])
print(marks[sort])

['Charlie' 'Bob' 'Eve' 'Alice' 'David']
[78 85 88 92 95]


#### Demonstrate the concept of array partitioning:

Partition a 1D array to bring the smallest `k` elements to the front without full sorting.

In [35]:
arr = np.array([9, 4, 7, 2, 10, 5, 8, 1, 6, 3])

partition = np.partition(arr , 4)
print(partition)

partition = np.partition(arr , 3)
partition

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Apply partitioning to a 2D array to isolate the top 3 smallest values in each row.


In [55]:
arr_2d = np.array([[10, 50, 20, 90, 60],[35, 15, 85, 25, 55],[77, 44, 99, 11, 22]])

partition = np.partition(arr_2d , "k" == 3 , axis = 1)
print(partition)

## top 3 smallest values in each row.
print(partition[:, :3])

[[10 20 50 60 90]
 [15 25 35 55 85]
 [11 22 44 77 99]]
[[10 20 50]
 [15 25 35]
 [11 22 44]]


Compare the difference between `partition()` and `sort()` with suitable examples.

In [56]:
print(partition)
print(np.sort(arr_2d))

[[10 20 50 60 90]
 [15 25 35 55 85]
 [11 22 44 77 99]]
[[10 20 50 60 90]
 [15 25 35 55 85]
 [11 22 44 77 99]]
